export const proveedorFields = [
  {
    name: "nombre",
    label: "Nombre",
    type: "text",
    placeholder: "Nombre del proveedor",
    required: true,
    minLength: 3,
    maxLength: 80,
  },
  {
    name: "contacto",
    label: "Contacto",
    type: "text",
    placeholder: "Nombre del contacto",
    required: true,
  },
  {
    name: "telefono",
    label: "Teléfono",
    type: "tel",
    placeholder: "310-000-0000",
    required: true,
  },
  {
    name: "email",
    label: "Correo electrónico",
    type: "email",
    placeholder: "correo@ejemplo.com",
  },
  {
    name: "ciudad",
    label: "Ciudad",
    type: "text",
    placeholder: "Ciudad",
    required: true,
  },
  {
    name: "activo",
    label: "Estado",
    type: "select",
    required: true,
    options: [
      { value: "true",  label: "Activo" },
      { value: "false", label: "Inactivo" },
    ],
  },
  {
    name: "notas",
    label: "Notas",
    type: "textarea",
    placeholder: "Observaciones adicionales…",
    fullWidth: true,
  },
];

export const insumoFields = [
  {
    name: "nombre",
    label: "Nombre",
    type: "text",
    placeholder: "Nombre del insumo",
    required: true,
    minLength: 2,
  },
  {
    name: "categoria",
    label: "Categoría",
    type: "select",
    required: true,
    options: [
      { value: "Granos",      label: "Granos" },
      { value: "Aceites",     label: "Aceites" },
      { value: "Endulzantes", label: "Endulzantes" },
      { value: "Condimentos", label: "Condimentos" },
      { value: "Aditivos",    label: "Aditivos" },
      { value: "Lácteos",     label: "Lácteos" },
    ],
  },
  {
    name: "unidad",
    label: "Unidad de medida",
    type: "select",
    required: true,
    options: [
      { value: "kg",  label: "Kilogramo (kg)" },
      { value: "lt",  label: "Litro (lt)" },
      { value: "gr",  label: "Gramo (gr)" },
      { value: "und", label: "Unidad (und)" },
    ],
  },
  {
    name: "stock",
    label: "Stock inicial",
    type: "number",
    placeholder: "0",
    required: true,
    min: 0,
  },
  {
    name: "stockMinimo",
    label: "Stock mínimo",
    type: "number",
    placeholder: "0",
    required: true,
    min: 1,
  },
  {
    name: "precio",
    label: "Precio unitario ($)",
    type: "number",
    placeholder: "0",
    required: true,
    min: 0,
  },
];

export const productoFields = [
  {
    name: "nombre",
    label: "Nombre del producto",
    type: "text",
    placeholder: "Nombre",
    required: true,
    minLength: 2,
  },
  {
    name: "categoria",
    label: "Categoría",
    type: "select",
    required: true,
    options: [
      { value: "Bebidas",   label: "Bebidas" },
      { value: "Snacks",    label: "Snacks" },
      { value: "Lácteos",   label: "Lácteos" },
      { value: "Panadería", label: "Panadería" },
    ],
  },
  {
    name: "precio",
    label: "Precio de venta ($)",
    type: "number",
    placeholder: "0",
    required: true,
    min: 0,
  },
  {
    name: "stock",
    label: "Stock",
    type: "number",
    placeholder: "0",
    required: true,
    min: 0,
  },
  {
    name: "disponible",
    label: "Disponible",
    type: "select",
    required: true,
    options: [
      { value: "true",  label: "Sí" },
      { value: "false", label: "No" },
    ],
  },
  {
    name: "descripcion",
    label: "Descripción",
    type: "textarea",
    placeholder: "Descripción del producto…",
    fullWidth: true,
  },
];

export const pedidoFields = [
  {
    name: "cliente",
    label: "Cliente",
    type: "text",
    placeholder: "Nombre del cliente",
    required: true,
  },
  {
    name: "fecha",
    label: "Fecha",
    type: "date",
    required: true,
  },
  {
    name: "estado",
    label: "Estado",
    type: "select",
    required: true,
    options: [
      { value: "Pendiente",  label: "Pendiente" },
      { value: "En camino",  label: "En camino" },
      { value: "Entregado",  label: "Entregado" },
      { value: "Cancelado",  label: "Cancelado" },
    ],
  },
  {
    name: "total",
    label: "Total ($)",
    type: "number",
    placeholder: "0",
    required: true,
    min: 0,
  },
  {
    name: "notas",
    label: "Notas",
    type: "textarea",
    placeholder: "Observaciones del pedido…",
    fullWidth: true,
  },
];
